# Generated by Django 5.2.14 on 2026-08-28 14:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Telefone deve seguir o formato +5588999999999 (DDI + DDD + número).', regex='^\\+\\d{12,13}$')], verbose_name='telefone do cliente')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('closed', 'Encerrada')], default='active', max_length=16)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Última mensagem da conversa, seja do cliente ou do assistente.', null=True)),
            ],
            options={
                'verbose_name': 'conversa',
                'verbose_name_plural': 'conversas',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador externo')),
                ('role', models.CharField(choices=[('customer', 'Cliente'), ('assistant', 'Assistente')], max_length=16)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(help_text='Momento da mensagem informado pela origem, não o do INSERT.')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
            },
        ),
        migrations.CreateModel(
            name='PropertyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='conversations.conversation')),
                ('message', models.ForeignKey(blank=True, help_text='Mensagem do assistente que apresentou o imóvel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='conversations.message')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='properties.property')),
            ],
            options={
                'verbose_name': 'imóvel recomendado',
                'verbose_name_plural': 'imóveis recomendados',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='recommended_properties',
            field=models.ManyToManyField(blank=True, related_name='conversations', through='conversations.PropertyRecommendation', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='message_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyrecommendation',
            constraint=models.UniqueConstraint(fields=('conversation', 'property'), name='unique_property_per_conversation'),
        ),
    ]
