# Generated by Django 5.2.14 on 2026-08-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrecommendation',
            options={'verbose_name': 'imóvel recomendado', 'verbose_name_plural': 'imóveis recomendados'},
        ),
    ]
