# Generated by Django 5.2.14 on 2026-09-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_propertyrecommendation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrecommendation',
            name='message',
        ),
    ]
