# Generated by Django 5.2.14 on 2026-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_remove_propertyrecommendation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='external_conversation_id',
            field=models.CharField(null=True, verbose_name='ID Externo da Conversa (Provider)'),
        ),
    ]
