# Generated by Django 5.2.14 on 2026-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='código do imóvel')),
                ('transaction_type', models.CharField(choices=[('aluguel', 'Aluguel'), ('venda', 'Venda')], max_length=16, verbose_name='tipo de transação')),
                ('neighborhood', models.CharField(max_length=120, verbose_name='bairro')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço')),
                ('bedrooms', models.PositiveSmallIntegerField(verbose_name='quartos')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('source', models.CharField(default='csv', max_length=32, verbose_name='origem da carga')),
                ('source_reference', models.CharField(blank=True, help_text='Arquivo, endpoint ou identificador de onde o registro veio.', max_length=255)),
                ('imported_at', models.DateTimeField(blank=True, help_text='Momento da última carga que tocou este registro.', null=True)),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['transaction_type', 'neighborhood', 'price'], name='property_search_idx')],
            },
        ),
    ]
