# Generated by Django 5.2.14 on 2026-09-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='source_reference',
        ),
    ]
